const dotenv = require("dotenv");
dotenv.config();

const {
    SENDGRID_SEND_REMINDER_TEMPLATE_ID,
    SENDGRID_REGISTRATION_COMPLETED_TEMPLATE_ID,
    SENDGRID_UNREGISTRATION_COMPLETED_TEMPLATE_ID,
    SENDGRID_CONFIRM_REGISTRATION_TEMPLATE_ID,
    SENDGRID_CONFIRM_UNREGISTRATION_TEMPLATE_ID,
    SERVICE_EMAIL,
    SENDGRID_API_KEY
} = process.env;

module.exports = {
    sendReminderTemplateId: SENDGRID_SEND_REMINDER_TEMPLATE_ID,
    registrationCompletedTemplateId: SENDGRID_REGISTRATION_COMPLETED_TEMPLATE_ID,
    unregistrationCompletedTemplateId: SENDGRID_UNREGISTRATION_COMPLETED_TEMPLATE_ID,
    confirmUnregistrationTemplateId: SENDGRID_CONFIRM_UNREGISTRATION_TEMPLATE_ID,
    confirmRegistrationTemplateId: SENDGRID_CONFIRM_REGISTRATION_TEMPLATE_ID,
    serviceEmail: SERVICE_EMAIL,
    sendgridApiKey: SENDGRID_API_KEY
};